"""initial migration

Revision ID: c2e38f8947b1
Revises:
Create Date: 2026-01-09 11:14:21.019187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e38f8947b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demirbas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('marka', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('seri_no', sa.String(length=50), nullable=True),
    sa.Column('demirbas_no', sa.String(length=50), nullable=False),
    sa.Column('cinsi', sa.String(length=50), nullable=True),
    sa.Column('alim_tarihi', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('konum', sa.String(length=100), nullable=True),
    sa.Column('kampus', sa.String(length=100), nullable=True),
    sa.Column('birim', sa.String(length=100), nullable=True),
    sa.Column('adet', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('qr_kod', sa.String(length=200), nullable=True),
    sa.Column('fotograf', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demirbas_no'),
    sa.UniqueConstraint('seri_no')
    )
    with op.batch_alter_table('demirbas', schema=None) as batch_op:
        batch_op.create_index('idx_demirbas_ad', ['ad'], unique=False)
        batch_op.create_index('idx_demirbas_kampus', ['kampus'], unique=False)
        batch_op.create_index('idx_demirbas_konum', ['konum'], unique=False)

    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sifre', sa.String(length=200), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=True),
    sa.Column('birim', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('yetki_duzeyi', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('personel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(length=100), nullable=True),
    sa.Column('unvan', sa.String(length=100), nullable=True),
    sa.Column('birimi', sa.String(length=100), nullable=True),
    sa.Column('sicil_no', sa.String(length=50), nullable=True),
    sa.Column('ofis', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('baslama_tarihi', sa.String(length=20), nullable=True),
    sa.Column('kampus', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yukleme_gecmisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('tarih', sa.String(length=30), nullable=True),
    sa.Column('islem_yapan', sa.String(length=100), nullable=True),
    sa.Column('tur', sa.String(length=50), nullable=True),
    sa.Column('hedef_konum', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ariza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('oncelik', sa.String(length=20), nullable=True),
    sa.Column('konum', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('bildiren', sa.String(length=100), nullable=True),
    sa.Column('demirbas_id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demirbas_id'], ['demirbas.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ariza', schema=None) as batch_op:
        batch_op.create_index('idx_ariza_demirbas_id', ['demirbas_id'], unique=False)
        batch_op.create_index('idx_ariza_durum', ['durum'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ariza', schema=None) as batch_op:
        batch_op.drop_index('idx_ariza_durum')
        batch_op.drop_index('idx_ariza_demirbas_id')

    op.drop_table('ariza')
    op.drop_table('yukleme_gecmisi')
    op.drop_table('personel')
    op.drop_table('kullanici')
    with op.batch_alter_table('demirbas', schema=None) as batch_op:
        batch_op.drop_index('idx_demirbas_konum')
        batch_op.drop_index('idx_demirbas_kampus')
        batch_op.drop_index('idx_demirbas_ad')

    op.drop_table('demirbas')
    # ### end Alembic commands ###
